### ISSUE TITLE
Switch to disable build-xhtml-email

### ISSUE THREAD

**Issue by deadtrickster** [u-u-h/cl-sendmail#3]
It would be nice to have a swtich that can turn `build-xhtml-email` off. Actually in my fork I commented whole (when "text/html"... ) block.

**Comment by u-u-h** [comment]
I'll look into this; since you already forked a copy could you maybe propose a patch and make a pull request against this issue?

uuh

**Comment by u-u-h** [comment]
Hmm, what are you trying to accomplish -- or when does having build-xhtml-email break for you?

If you disabling it because you want to (opaquely) pass ready-made html into the mail, then a switch like 'bypass-xhtml-cleanup' might do. But the idea of build-xhtml-email is that it (destructively) replaces references to images by references to the attachment containing the image, which usually is a good idea (since otherwise you can't be sure that the recipient can locate the image).

uuh

**Comment by deadtrickster** [comment]
Hey, thanks for fast reply!

Yes I'm passing ready-to-go html with everything setup as needed. 

I'm thinking about new parameter, something like `:dont-be-clever-than-me` or maybe if message is string do not touch it but if it is DOM the go with processing?. What you think?

**Comment by u-u-h** [comment]
I'd prefer not to dispatch on the message data type (string vs. DOM), such magic will bite someone and will be hard to figure out. 
I assume that you are creating a mail-output-stream with subtype 'html' somewhere; I'm not sure why we don't have a subclass of mail-output-stream like mail-output-stream/html for this common case. If we can introduce one without breaking backward compatibility we could introduce another one like mail-output-stream/raw-html that is 'unparsed' like you want. Would that work for you?

uuh

**Comment by deadtrickster** [comment]
Stream type determined here https://github.com/u-u-h/cl-sendmail/blob/master/sendmail.lisp#L138 based on parameters. Since with-email is primary entry point (and I actually use it) I think adding parameter like (raw-html nil) is a good idea. Based on its value stream of type `mail-output-stream/html` or `mail-output-stream/raw-html` can be created. `build-xhtml-email` can possibly be renamed to `process-xhtml-email` and converted to defmethod. This doesn't break things and fits me, What you think?

**Comment by u-u-h** [comment]
Sounds like a reasonable way to handle it. What I don't like is that a reference to subtype 'html' appears in the with-email signature; it should be content-(subtype)-agnostic. I'll try to figure out whether that can be avoided. Maybe a 'process-mail-body' function that defaults to something that by default doesn't do much, but for html enters the current path. Then a 'do-nothing' function that you can plug in for your use case (maybe even #'identity can be made to work). Might even avoid the the subclassing I suggested yesterday mirroring mime.types which is also overdoing things, in particular if we basically only do it for html.

uuh
